# Generated by Django 5.1.1 on 2024-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webrtc_public', models.CharField(blank=True, max_length=32, null=True)),
                ('webrtc_private', models.CharField(blank=True, max_length=32, null=True)),
                ('position_longitude', models.FloatField(blank=True, null=True)),
                ('position_latitude', models.FloatField(blank=True, null=True)),
                ('position_accuracy', models.FloatField(blank=True, null=True)),
                ('position_altitude', models.FloatField(blank=True, null=True)),
                ('languages_js', models.CharField(blank=True, max_length=32, null=True)),
                ('languages_http', models.CharField(blank=True, max_length=256, null=True)),
                ('languages_lang', models.CharField(blank=True, max_length=32, null=True)),
                ('timezone', models.CharField(blank=True, max_length=32, null=True)),
                ('webgl_vendor', models.CharField(blank=True, max_length=32, null=True)),
                ('webgl_renderer', models.CharField(blank=True, max_length=256, null=True)),
                ('hardware_memory', models.FloatField(blank=True, null=True)),
                ('hardware_concurrency', models.FloatField(blank=True, null=True)),
                ('mobile_touchsupport', models.FloatField(blank=True, null=True)),
                ('screen_width', models.FloatField(blank=True, null=True)),
                ('screen_height', models.FloatField(blank=True, null=True)),
                ('screen_colorDepth', models.FloatField(blank=True, null=True)),
                ('screen_availHeight', models.FloatField(blank=True, null=True)),
                ('screen_availWidth', models.FloatField(blank=True, null=True)),
                ('clientrect_x', models.FloatField(blank=True, null=True)),
                ('clientrect_y', models.FloatField(blank=True, null=True)),
                ('Canvas_todataURL', models.FloatField(blank=True, null=True)),
                ('Canvas_height', models.FloatField(blank=True, null=True)),
                ('Canvas_width', models.FloatField(blank=True, null=True)),
                ('webaudio_value', models.FloatField(blank=True, null=True)),
                ('gpu_device', models.CharField(blank=True, max_length=32, null=True)),
                ('gpu_description', models.CharField(blank=True, max_length=256, null=True)),
                ('useragent_big', models.CharField(blank=True, max_length=256, null=True)),
                ('useragent_little', models.CharField(blank=True, max_length=256, null=True)),
                ('clientHint_navigator_platform', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_platform', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_platformVersion', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_uaFullVersion', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_architecture', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_bitness', models.CharField(blank=True, max_length=32, null=True)),
                ('clientHint_browser', models.CharField(blank=True, max_length=32, null=True)),
                ('font_removefont', models.CharField(blank=True, max_length=256, null=True)),
                ('font_removefont_2', models.CharField(blank=True, max_length=256, null=True)),
                ('dnsleak_enable', models.CharField(blank=True, max_length=32, null=True)),
                ('portScan_enable', models.CharField(blank=True, max_length=32, null=True)),
                ('software_cookie', models.CharField(blank=True, max_length=32, null=True)),
                ('software_java', models.CharField(blank=True, max_length=32, null=True)),
                ('software_dnt', models.CharField(blank=True, max_length=32, null=True)),
                ('proxy_user_data_dir', models.CharField(blank=True, max_length=256, null=True)),
                ('proxy_type', models.CharField(blank=True, max_length=32, null=True)),
                ('proxy_username', models.CharField(blank=True, max_length=32, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=32, null=True)),
                ('proxy_ipport', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
