from django.db import models

# Create your models here.
class FingersModel(models.Model):
    webrtc_public = models.CharField(max_length=32, null=True, blank=True)
    webrtc_private = models.CharField(max_length=32, null=True, blank=True)
    position_longitude = models.FloatField(null=True, blank=True)
    position_latitude = models.FloatField(null=True, blank=True)
    position_accuracy = models.FloatField(null=True, blank=True)
    position_altitude = models.FloatField(null=True, blank=True)
    languages_js = models.CharField(max_length=32, null=True, blank=True)
    languages_http = models.CharField(max_length=256, null=True, blank=True)
    languages_lang = models.CharField(max_length=32, null=True, blank=True)
    timezone = models.CharField(max_length=32, null=True, blank=True)
    webgl_vendor = models.CharField(max_length=32, null=True, blank=True)
    webgl_renderer = models.CharField(max_length=256, null=True, blank=True)
    hardware_memory = models.FloatField(null=True, blank=True)
    hardware_concurrency = models.FloatField(null=True, blank=True)
    mobile_touchsupport = models.FloatField(null=True, blank=True)
    screen_width = models.FloatField(null=True, blank=True)
    screen_height = models.FloatField(null=True, blank=True)
    screen_colorDepth = models.FloatField(null=True, blank=True)
    screen_availHeight = models.FloatField(null=True, blank=True)
    screen_availWidth = models.FloatField(null=True, blank=True)
    clientrect_x = models.FloatField(null=True, blank=True)
    clientrect_y = models.FloatField(null=True, blank=True)
    Canvas_todataURL = models.FloatField(null=True, blank=True)
    Canvas_height = models.FloatField(null=True, blank=True)
    Canvas_width = models.FloatField(null=True, blank=True)
    webaudio_value = models.FloatField(null=True, blank=True)
    gpu_device = models.CharField(max_length=32, null=True, blank=True)
    gpu_description = models.CharField(max_length=256, null=True, blank=True)
    useragent_big = models.CharField(max_length=256, null=True, blank=True)
    useragent_little = models.CharField(max_length=256, null=True, blank=True)
    clientHint_navigator_platform = models.CharField(max_length=32, null=True, blank=True)
    clientHint_platform = models.CharField(max_length=32, null=True, blank=True)
    clientHint_platformVersion = models.CharField(max_length=32, null=True, blank=True)
    clientHint_uaFullVersion = models.CharField(max_length=32, null=True, blank=True)
    clientHint_mobile = models.CharField(max_length=32, null=True, blank=True)
    clientHint_architecture = models.CharField(max_length=32, null=True, blank=True)
    clientHint_bitness = models.CharField(max_length=32, null=True, blank=True)
    clientHint_browser = models.CharField(max_length=32, null=True, blank=True)
    font_removefont = models.CharField(max_length=256, null=True, blank=True)
    font_removefont_2 = models.CharField(max_length=256, null=True, blank=True)
    dnsleak_enable = models.CharField(max_length=32, null=True, blank=True)
    portScan_enable = models.CharField(max_length=32, null=True, blank=True)
    software_cookie = models.CharField(max_length=32, null=True, blank=True)
    software_java = models.CharField(max_length=32, null=True, blank=True)
    software_dnt = models.CharField(max_length=32, null=True, blank=True)
    proxy_user_data_dir = models.CharField(max_length=256, null=True, blank=True)
    proxy_type = models.CharField(max_length=32, null=True, blank=True)
    proxy_username = models.CharField(max_length=32, null=True, blank=True)
    proxy_password = models.CharField(max_length=32, null=True, blank=True)
    proxy_ipport = models.CharField(max_length=32, null=True, blank=True)